### ISSUE TITLE
Remove bitcoin core minor versions?

### ISSUE THREAD

**Issue by RCasatta** [RCasatta/bitcoind#120]
There are 12 Bitcoin core versions available with auto-download features.
To clean up a little bit and save CI jobs I was thinking to remove minor versions if someone doesn't object on this issue in the next months.

Versions removed would be: 
- 0.18.0
- 0.19.0.1
- 0.20.0
- 0.21.0

**Comment by apoelstra** [comment]
Yeah, this seems totally reasonable to me.
