### ISSUE TITLE
Migrate to rust `1.57.0`, is someone relying on MSRV `1.48.0` ?

### ISSUE THREAD

**Issue by RCasatta** [RCasatta/bitcoind#135]
The objective of this crate is to keep the same MSRV as `rust-bitcoin` which is currently 1.48.0

However, I am struggling to keep the MSRV to 1.48.0 because all the deps are breaking it, in fact, currently, the MSRV is not respected as shown by failing jobs in CI.

I am planning to move to 1.57 unless someone replies to this issue with good arguments.

related: https://github.com/rust-bitcoin/rust-bitcoin/discussions/1983

**Comment by RCasatta** [comment]
Sure, I will not upgrade explicitly no-features MSRV explicitly until rust-bitcoin do it...

But currently I don't know which deps must be pinned to achieve that, see #134

**Comment by apoelstra** [comment]
As I recall, the "bad" deps are all related to the HTTP download stuff. So if you use it with a fixed BITCOIND_EXE env var (as we do, at least in our Nix-based tests) then you avoid all the bad ones.

**Comment by RCasatta** [comment]
finally found a combination of pinning so that #134 is fixed, closing for now

I know it's not rust-bitcoin fault and the issue are dependencies updating MSRV in their minor versions, but I hope we upgrade our MSRV because this task is annoying
