### ISSUE TITLE
Look in path for bitcoind

### ISSUE THREAD

**Issue by JonathanLorimer** [RCasatta/bitcoind#57]
Is there any way to provide the `bitcoind` binary via the `PATH` env var? Specifically in `build.rs`. I am trying to package this [project](https://github.com/nomic-io/nomic) with nix, which strips some of the non-deterministic attributes from gzipped files when generating a checksum, therefore I am getting a different hash than the one you specified [here](https://github.com/RCasatta/bitcoind/blob/master/sha256/bitcoin-core-22.0-SHA256SUMS#L18). I do have access to bitcoind v22.0 in nix though, and could easily provide a reference to the binary.

**Comment by RCasatta** [comment]
> Is there any way to provide the bitcoind binary via the PATH env var? 

There isn't at the moment, but I think it makes sense to search there if no feature and no BITCOIND_EXE are provided.
I will work on a PR for it
