### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by johncantrell97** [RCasatta/bitcoind#67]
Looks like the build script is missing support for windows platforms.  Assuming that there just wasn't any need for this and that there's not some fundamental problem.  From my limited look at the codebase seems like we just need to implement a download_filename implementation for windows?

**Comment by RCasatta** [comment]
I don't recall any fundamental problem in supporting windows.

For a valid PR adding the support, other than what you are mentioning, will be needed a new Github action job running on windows to test the compatibility in the CI
