### ISSUE TITLE
Cannot use `-rpcuser` and `-rpcpassword` as arguments, does not return Err and enters infinite loop

### ISSUE THREAD

**Issue by oleonardolima** [RCasatta/bitcoind#68]
**Describe the bug**  
Cannot use `-rpcuser=<user>` and `-rpcpassword=<password>` args with `bitcoind`, although it's indicated to be deprecated when running `bitcoind` from the binaries I think it's useful and would be great to maintain compatibility.

The `-rpcuser` and `-rpcpassword` does not create a `.cookie` file, therefore it produces an error when trying to read from the file and get auth parameters.

It enters in an infinite loop because it cannot create and connect a RPC client in step: [`let client_result = Client::new(&rpc_url, Auth::CookieFile(cookie_file.clone()));`](https://github.com/RCasatta/bitcoind/blob/master/src/lib.rs#L301) when calling `auth.get_user_pass` it returns an io error because the file does not exists, but the error is not treated and it skip to another pass in the loop considering it's just because the process is not up yet.

It would be better to not consider the .cookie file when receiving `-rpcuser` and `-rpcpassword` arguments or raise an error recommending to use `-rpcauth`, which works because it uses user and password and creates a .cookie file, and I'm using as a workaround. 

**To Reproduce** 
You can simply try to start a process passing the  `-rpcauth` and `-rpcpassword` as arguments in conf, it won't event start the process.
I've created two tests here: https://github.com/oleonardolima/bitcoind/commit/b522d5ec1c42584b81c3b6595e36b9df0b2517f6
- one for reproducing the error for `-rpcuser` and `-rpcpassword`, recommended to run with debug logs: https://github.com/RCasatta/bitcoind/commit/b522d5ec1c42584b81c3b6595e36b9df0b2517f6#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R621-R643
- one to show that for `-rpcauth` works successfully: https://github.com/RCasatta/bitcoind/commit/b522d5ec1c42584b81c3b6595e36b9df0b2517f6#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R645-R668

**Expected behavior**  
I expect that it would work successfully or return an error indicating that it's indicated to use -rpcauth instead.

**Build environment**  
 - bitcoind tag/commit: `v0.13.0` | `bd952c186ffa30e328a7b12c350569856b43c7c1` 
 - OS+version: `macOS 12.4`  
 - Rust/Cargo version: `rustc 1.60.0 (7737e0b5c 2022-04-04)` | `cargo 1.60.0 (d1fd9fe2c 2022-03-01)`
 - Rust/Cargo target: `aarch64-apple-darwin`

**Comment by oleonardolima** [comment]
@RCasatta Please let me know if the bug makes sense or was an expected behavior, and if any more info is needed.

If it either needs to fix to return an error or to accept the arguments and not consider the .cookie file I will more than help to discuss a solution, build the fix, and open a PR.

**Comment by RCasatta** [comment]
cookie support dates back to bitcoin core version 0.12, do you need to test with versions prior to this?

I think we should probably prevent users to specify `rpcuser` and `rpcpassword` and give a proper error.

**Comment by oleonardolima** [comment]
I need to use a custom user and password but didn't notice that it's deprecated, using the -rpcauth works fine.

Great, a specific error would've saved me some time 😅 

I'll work in a PR candidate to fix and update to give a proper error.

**Comment by MaxFangX** [comment]
Thanks for opening this issue - I was using `rpcuser` / `rpcpassword`, and seeing that there were problems with it saved me a bunch of debugging. If `rpcuser` / `rpcpassword` are known not to work, perhaps it should be documented somewhere? I had the assumption that although those options were deprecated in `bitcoind`, they would still be generally work, as this crate seems to be a relatively thin wrapper around `bitcoind`.

**Comment by oleonardolima** [comment]
@MaxFangX I'm really glad that the issue helped and saved you a lot of time, I've used a lot of time to figure out the problem 😅 

I've not finished my work on a draft PR due to my final exams and SoB project

I'll try to open it in the next few days to add a better error message as discussed with RCasatta above.

**Comment by oleonardolima** [comment]
@RCasatta I've now opened PR #72 related to this issue, would really appreciate a review.

I think would also be useful to have a function to produce the `-rpcauth` expected value, wdyt ?

I can port the bitcoin core python script like this one: https://github.com/testcontainers/testcontainers-rs/blob/dev/testcontainers/src/images/coblox_bitcoincore.rs#L40-L91

> cc @MaxFangX
