### ISSUE TITLE
Upgrade bitcoincore-rpc depency

### ISSUE THREAD

**Issue by tcharding** [RCasatta/bitcoind#82]
Soon as https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/234 merges we can upgrade the bitcoincore-rpc dependency allowing `rust-miniscript` to upgrade `rust-bitcoin`.

**Comment by josediegorobles** [comment]
Hi, https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/234 it's merged now, bitcoind can be update yet?

**Comment by tcharding** [comment]
We need a release of `rust-bitcoincore-rpc` with first, @josediegorobles. I'll do a PR.

**Comment by josediegorobles** [comment]
> We need a release of `rust-bitcoincore-rpc` first @josediegorobles.

Ok, it's done: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/releases/tag/v0.16.0

**Comment by RCasatta** [comment]
> Ok, it's done: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/releases/tag/v0.16.0 @tcharding

https://github.com/RCasatta/bitcoind/pull/84

**Comment by tcharding** [comment]
Thanks man.
