### ISSUE TITLE
Why using ureq instead of rust-jsonrpc?

### ISSUE THREAD

**Issue by apoelstra** [RCasatta/bitcoind#87]
rust-jsonrpc has a simple HTTP client which does not have dependencies that break compilation.

**Comment by RCasatta** [comment]
Because until now I didn't know I could use it as a generic HTTP client!

**Comment by apoelstra** [comment]
It's fairly new :) if you try it and it doesn't work please file a bug!

**Comment by RCasatta** [comment]
I checked jsonrpc and I don't think it's suitable.
I am using ureq as a build dep to download bitcoin binaries from bitcoincore.org if the "automatic download version" feature is activated.

**Comment by apoelstra** [comment]
Ah -- no. I have filed an issue https://github.com/apoelstra/rust-jsonrpc/issues/71 and will close this one for now. Thanks!
