### ISSUE TITLE
error messages contain no context

### ISSUE THREAD

**Issue by apoelstra** [RCasatta/bitcoind#90]
When running `cargo test` on elements-miniscript from a non-`master` worktree I get
```
---- test_setup stdout ----
thread 'test_setup' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/setup/mod.rs:23:86
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
the relevant line is
```
    if validate_pegin {
        let bitcoind_exe = bitcoind::exe_path().unwrap();
        let bitcoind_conf = bitcoind::Conf::default();
        bitcoind = Some(bitcoind::BitcoinD::with_conf(&bitcoind_exe, &bitcoind_conf).unwrap()); // this unwrap is the error
    }   
```
There is nothing I can do with this. The test binary does some forking crap so I can't strace it.

**Comment by RCasatta** [comment]
I tried `cargo test` from a random branch: `remove_assert` and I didn't hit the error.

With the activated features `["0_21_0","bitcoind_22_0"]`  `elementsd` and `bitcoind` are downloaded in the target directory so by doing:

```
find target/ -name bitcoind
```

and 

```
chmod -x target/debug/build/bitcoind-266d42b48d35cf33/out/bitcoin/bitcoin-22.0/bin/bitcoind
```

I can reproduce the error.

has your downloaded bitcoind executable permission to execute?

**Comment by apoelstra** [comment]
>has your downloaded bitcoind executable permission to execute?

Ah, this was it. Ok, so I solved my particular problem (though I wonder how this happened..) but I do think we should use `anyhow` or something to add better error details.

**Comment by RCasatta** [comment]
> though I wonder how this happened

Yeah, I wonder too...

https://github.com/RCasatta/bitcoind/pull/93 should give more context

```
---- test::test_bitcoind stdout ----
thread 'test::test_bitcoind' panicked at 'called `Result::unwrap()` on an `Err` value: The binary "/home/casatta/git/bitcoind/target/debug/build/bitcoind-9bf12276f285d442/out/bitcoin/bitcoin-23.0/bin/bitcoind" has no permission to execute', src/lib.rs:502:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kixunil** [comment]
> The test binary does some forking crap so I can't strace it.

Just FYI for the future there's `strace -f` which traces all children recursively. Saved my butt a number of times.

**Comment by RCasatta** [comment]
https://github.com/RCasatta/bitcoind/pull/94 should have improved situation
