### ISSUE TITLE
v27.1 is NOT 1.41.1 MSRV because of ureq

### ISSUE THREAD

**Issue by DanGould** [RCasatta/bitcoind#95]
ureq = "1.0" allows ureq 1.6 to be installed. 1.6 depends on once_cell v1.16.0 which is not msrv 1.41.1. once_cell 1.9.0 is te latest version of at msrv 1.41.1. [once_cell 1.10.0 breaks it](https://github.com/matklad/once_cell/blob/v1.14.0/CHANGELOG.md#1100).

Unfortunately, ureq [does not adhere to any MSRV](https://github.com/algesten/ureq/issues/543), and only specifies `once_cell = "1"`

it seems this crate only has 1 ureq call, here https://github.com/RCasatta/bitcoind/blob/2c1758a2d5d638a388906c97bc011802b12e498b/build.rs#L106

so maybe the whole dependency could be replaced with something that maintains an MSRV

This is causing problems downstream. https://github.com/Kixunil/payjoin/pull/36

**Comment by RCasatta** [comment]
Any suggestion to adhere to MSRV on 27.x branch is welcome

**Comment by DanGould** [comment]
Even with `cargo update -p once_cell --precise 1.9.0` and building `ureq` in isolation msrv appears to be 1.54 for ureq 1.9.0. Further investigation is required.

**Comment by RCasatta** [comment]
@DanGould have a look at #102 which is a compromise, it allows MSRV 1.41.1 if the auto-download feature is not used

**Comment by RCasatta** [comment]
https://github.com/RCasatta/bitcoind/pull/102#issuecomment-1374878817 I think it's solved
